#!/usr/bin/env bash
# Check if an argument was passed

if [ "$#" -eq 1 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

# Ping the IP address 5 times
ping -c 5 "$IP_ADDRESS"
