#!/usr/bin/env bash
#Bash script that configures an Ubuntu server

cp /etc/hosts /etc/hosts.new
sed -i s/127.*$/127.0.0.2\\tlocalhost\\n8.8.8.8\\tfacebook.com/g /etc/hosts.new
cp -f /etc/hosts.new /etc/hosts
